// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardUserSmall: typeof import('./components/CardUserSmall.vue')['default']
    Collapse: typeof import('./components/Collapse.vue')['default']
    CollectiveCard: typeof import('./components/CollectiveCard.vue')['default']
    Container: typeof import('./components/layouts/Container.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FormButton: typeof import('./components/forms/FormButton.vue')['default']
    FormInput: typeof import('./components/forms/FormInput.vue')['default']
    FormRadio: typeof import('./components/forms/FormRadio.vue')['default']
    FormTextarea: typeof import('./components/forms/FormTextarea.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./components/Tabs.vue')['default']
  }
}

export {}
